---
--- Generated by Luanalysis
--- Created by tuiu.
--- DateTime: 2023/7/9 19:01
---
local nvimtree = require("nvim-tree")

local config = {
  view = {
    width = 30,
  }
}

nvimtree.setup(config);
