---
--- Generated by Luanalysis
--- Created by tuiu.
--- DateTime: 2023/7/9 17:07
---

-- Basic Setup
local opt = vim.opt;

-- number
opt.number = true;
opt.relativenumber = true;

-- tabstop
opt.tabstop = 2;
opt.softtabstop = 2;
opt.shiftwidth = 2;
opt.expandtab = true;


local keymap = vim.keymap.set;

keymap("n", "J", "5j");
keymap("n", "K", "5k");
keymap("n", "H", "5h");
keymap("n", "L", "5l");
keymap("v", "J", "5j");
keymap("v", "K", "5k");
keymap("v", "H", "5h");
keymap("v", "L", "5l");

keymap("n", "S", ":w<CR>");
keymap("n", "Q", ":q<CR>");
