---
--- Generated by Luanalysis
--- Created by tuiu.
--- DateTime: 2023/7/9 18:19
---

vim.cmd [[packadd packer.nvim]]

return require("packer").startup(function(use)
  --- Packer can manager itself
  use "wbthomason/packer.nvim";
end)
