---
--- Generated by Luanalysis
--- Created by tuiu.
--- DateTime: 2023/7/9 18:33
---

local ui = {};

ui["nvim-tree/nvim-tree.lua"] = {
  requires = { "nvim-tree/nvim-web-devicons" },
  config = function()
    require("modules.config.nvim-tree")
  end
}

return ui;
