---
--- Generated by Luanalysis
--- Created by tuiu.
--- DateTime: 2023/7/9 18:33
---

local ui = {};

ui["nvim-tree/nvim-tree.lua"] = {
  requires = { "nvim-tree/nvim-web-devicons" },
  config = function()
    require("modules.config.nvim-tree")
  end
}

ui["navarasu/onedark.nvim"] = {
  config = function()
    require("onedark").load()
  end
}

ui["akinsho/bufferline.nvim"] = {
  tag = "*",
  requires = { "nvim-tree/nvim-web-devicons" },
  config = function ()
    require("bufferline").setup();
  end
}

ui["nvim-lualine/lualine.nvim"] = {
  requires = { "nvim-tree/nvim-web-devicons", opt = true },
  config = function ()
    require("modules.config.evil_lualine");
  end
}

ui["nvim-telescope/telescope.nvim"] = {
  tag = "0.1.2",
  requires = { "nvim-lua/plenary.nvim" },
}

ui["nvim-treesitter/nvim-treesitter"] = {
  run = { ":TSUpdate" },
  config = function ()
    require("modules.config.treesitter")
  end
}

return ui;
