---
--- Generated by Luanalysis
--- Created by tuiu.
--- DateTime: 2023/7/9 17:40
---

local keymap = vim.keymap.set;

function nmap(...)
  keymap("n", ...);
end

function vmap(...)
  keymap("v", ...);
end

local normal_keymaps = {
  ["J"] = { action = "5j", desc = "move to down 5 line" },
  ["K"] = { action = "5k", desc = "move to up 5 line" },
  ["H"] = { action = "7h", desc = "move to left 7 char" },
  ["L"] = { action = "7l", desc = "move to right 7 char" },
  ["S"] = { action = ":w<CR>", desc = "Save File" },
  ["Q"] = { action = ":q<CR>", desc = "Quit File" },
  ["<C-j>"] = { action = "<C-w>j", desc = "move cursor to down panel" },
  ["<C-k>"] = { action = "<C-w>k", desc = "move cursor to up panel" },
  ["<C-h>"] = { action = "<C-w>h", desc = "move cursor to left panel" },
  ["<C-l>"] = { action = "<C-w>l", desc = "move cursor to right panel" },
};

local visible_keymaps = {
  ["J"] = { action = "5j", desc = "move to down 5 line" },
  ["K"] = { action = "5k", desc = "move to up 5 line" },
  ["H"] = { action = "7h", desc = "move to left 7 char" },
  ["L"] = { action = "7l", desc = "move to right 7 char" },
}


local default_opts = {
  silent = true,
  desc = "",
}

for key, opts in pairs(normal_keymaps) do
  if opts.desc then
    default_opts.desc = opts.desc;
  end
  nmap(key, opts.action, default_opts);
end

for key, opts in pairs(visible_keymaps) do
  if opts.desc then
    default_opts.desc = opts.desc;
  end
  vmap(key, opts.action, default_opts);
end
