---
--- Generated by Luanalysis
--- Created by tuiu.
--- DateTime: 2023/7/9 17:40
---

local utils = require("core.utils");

local normal_keymaps = {
  ["J"] = { action = "5j", desc = "move to down 5 line" },
  ["K"] = { action = "5k", desc = "move to up 5 line" },
  ["H"] = { action = "7h", desc = "move to left 7 char" },
  ["L"] = { action = "7l", desc = "move to right 7 char" },
  ["S"] = { action = ":w<CR>", desc = "Save File" },
  ["Q"] = { action = ":q<CR>", desc = "Quit File" },
  ["<C-j>"] = { action = "<C-w>j", desc = "move cursor to down panel" },
  ["<C-k>"] = { action = "<C-w>k", desc = "move cursor to up panel" },
  ["<C-h>"] = { action = "<C-w>h", desc = "move cursor to left panel" },
  ["<C-l>"] = { action = "<C-w>l", desc = "move cursor to right panel" },
};

local visible_keymaps = {
  ["J"] = { action = "5j", desc = "move to down 5 line" },
  ["K"] = { action = "5k", desc = "move to up 5 line" },
  ["H"] = { action = "7h", desc = "move to left 7 char" },
  ["L"] = { action = "7l", desc = "move to right 7 char" },
}


local default_keymaps = {
  n = normal_keymaps,
  v = visible_keymaps,
}

local plugins_keymaps = {
  nvimtree = {
    n = {
      ["<SPACE>e"] = { action = ":NvimTreeToggle<CR>", desc = "toggle file exploer" }
    }
  },
  bufferline = {
    n = {
      ["<TAB>"] = { action = ":BufferLineCycleNext<CR>", desc = "next buffer" },
      ["<S-TAB>"] = { action = ":BufferLineCyclePrev<CR>", desc = "prev buffer" },
    }
  },
  telescope = {
    n = {
      ["<SPACE>ff"] = { action = ":Telescope find_files<CR>", desc = "open telescope find files" },
      ["<SPACE>fw"] = { action = ":Telescope live_grep<CR>", desc = "open telescope live grep" },
    }
  },
  packer = {
    n = {
      ["<SPACE>ps"] = { action = ":PackerSync<CR>", desc = "Packer Sync" },
      ["<SPACE>pi"] = { action = ":PackerInstall<CR>", desc = "Packer Install" },
      ["<SPACE>pp"] = { action = ":PackerUpdate<CR>", desc = "Packer Update" },
    }
  }
}

utils.loadKeymaps(default_keymaps);

for _, keymaps in pairs(plugins_keymaps) do
  utils.loadKeymaps(keymaps);
end
