---
--- Generated by Luanalysis
--- Created by tuiu.
--- DateTime: 2023/7/9 17:17
---

local default_config = {
  opt = {
    --- number
    number = true,
    relativenumber = true,

    --- colors
    termguicolors = true,
  },
  bo = {
    --- tabstop
    tabstop = 2,
    softtabstop = 2,
    expandtab = true,
    shiftwidth = 2,
    smartindent = true,
  }
}

for mode, config in pairs(default_config) do
  for key, value in pairs(config) do
    vim[mode][key] = value;
  end
end
