---
--- Generated by Luanalysis
--- Created by tuiu.
--- DateTime: 2023/7/9 18:47
---

local M = {};
local keymap = vim.keymap.set;

M.nmap = function (...) keymap("n", ...) end;
M.vmap = function (...) keymap("v", ...) end

M.MergeTables = function(...)
  local tabs = {...}
  if not tabs then
    return {};
  end
  local origin = tabs[1];
  for i = 2,#tabs do
    if origin then
      if tabs[i] then
        for k, v in pairs(tabs[i]) do
          if k then
            origin[k] = v;
          else
            table.insert(origin, v);
          end
        end
      end
    else
      origin = tabs[i];
    end
  end
  return origin;
end

M.loadPlugins = function(use, module)
  local uiPluginConfig = require("modules." .. module);
  for pluginUrl, pluginConfig in pairs(uiPluginConfig) do
    local config = M.MergeTables({pluginUrl}, pluginConfig);
    use(config);
  end
end

M.loadKeymaps = function (keymapConfig)
  for mode, keymaps in pairs(keymapConfig) do
    for key, opts in pairs(keymaps) do
      local default_opts = {
        silent = true,
        desc = "",
      }
      if opts.desc then
        default_opts.desc = opts.desc;
      end
      local map = nil;
      if mode == 'n' then
        map = M.nmap;
      elseif mode == 'v' then
        map = M.vmap;
      end
      map(key, opts.action, default_opts);
    end
  end
end

return M;
