---
--- Generated by Luanalysis
--- Created by tuiu.
--- DateTime: 2023/7/9 18:47
---

local M = {};
local keymap = vim.keymap.set;

M.nmap = function (...) keymap("n", ...) end;
M.vmap = function (...) keymap("v", ...) end

M.MergeTables = function(...)
  local tabs = {...}
  if not tabs then
    return {};
  end
  local origin = tabs[1];
  for i = 2,#tabs do
    if origin then
      if tabs[i] then
        for k, v in pairs(tabs[i]) do
          if k then
            origin[k] = v;
          else
            table.insert(origin, v);
          end
        end
      end
    else
      origin = tabs[i];
    end
  end
  return origin;
end

M.loadPlugins = function(use, module)
  local uiPluginConfig = require("modules." .. module);
  for pluginUrl, pluginConfig in pairs(uiPluginConfig) do
    local config = M.MergeTables({pluginUrl}, pluginConfig);
    use(config);
  end
end

M.loadKeymaps = function (keymapConfig)
  for mode, keymaps in pairs(keymapConfig) do
    for key, opts in pairs(keymaps) do
      local default_opts = {
        silent = true,
        desc = "",
      }
      if opts.desc then
        default_opts.desc = opts.desc;
      end
      local map = nil;
      if mode == 'n' then
        map = M.nmap;
      elseif mode == 'v' then
        map = M.vmap;
      end
      map(key, opts.action, default_opts);
    end
  end
end

M.maplsp = function (mapbuf)
  local opt = {
    silent = true
  }
  --- rename
  mapbuf("n", "<SPACE>rn", "<cmd>lua vim.lsp.buf.rename()<CR>", opt)
  --- code action
  mapbuf("n", "<SPACE>ca", "<cmd>lua vim.lsp.buf.code_action()<CR>", opt)
  -- go xx
  mapbuf('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<CR>', opt)
  mapbuf('n', 'gh', '<cmd>lua vim.lsp.buf.hover()<CR>', opt)
  mapbuf('n', 'gD', '<cmd>lua vim.lsp.buf.declaration()<CR>', opt)
  mapbuf('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opt)
  mapbuf('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opt)
  -- diagnostic
  mapbuf('n', 'go', '<cmd>lua vim.diagnostic.open_float()<CR>', opt)
  mapbuf('n', 'gp', '<cmd>lua vim.diagnostic.goto_prev()<CR>', opt)
  mapbuf('n', 'gn', '<cmd>lua vim.diagnostic.goto_next()<CR>', opt)
  -- mapbuf('n', '<leader>q', '<cmd>lua vim.diagnostic.setloclist()<CR>', opt)
  -- leader + =
  mapbuf('n', '<leader>=', '<cmd>lua vim.lsp.buf.formatting()<CR>', opt)
  -- mapbuf('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opt)
  -- mapbuf('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opt)
  -- mapbuf('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opt)
  -- mapbuf('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opt)
  -- mapbuf('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opt)
end

return M;
